export class BadWords {

    public badwords:Array<any> = [
        'vsf',
        'vtnc',
        'porra',
        'caralho',
        'buceta',
        'desgraca',
        'desgraça',
        'demonio',
        'capeta',
        'sastanas',
        'porra',
        'pau',
        'piru',
        'inferno',
        'caceta',
        'pura que pariu',
        'puta que pariu',
        'pqp',
        'foda-se',
        'foda se',
        'foda',
        'foda',
        'vai tomar no cu',
        'cu',
        'sexo',
        'piru',
        'gozada',
        'porno',
        'peitos',
        'buceta',
        'boquete',
        'pau no seu cu',
        'pau no cu',
        'pau no',
        'casa do caralho',
        'desgraçado',
        'peste',
        'puta',
        'piranha',
        'chupa',
        'chupa meu pau',
        'chupa meu cu',
        'gozar',
        'gozada',
        'boqueteira',
        'boqueteiro',
        'escroto',
        'ze buceta',
        'ze-buceta',
        'ze droguina',
        'drogas',
        'droga',
        'maconha',
        'cocaina',
        'crack',
        'pozinho',
        'ze droguinha',
        'vou te matar',
        'vou te pegar',
        'estuprar',
        'estrupar',
        'vou te estuprar',
        'vou te estrupar',
        'vou matar sua familia',
        'vou te comer',
        'comer seu cu',
        'comer voce',
        'comer você',
        'vai dar o cu',
        'vai dar a buceta',
        'vai pra merda'
    ]

    constructor(){}
    
}